### ISSUE TITLE
Add instructions for use

### ISSUE THREAD

**Issue by deevroman** [Zaczero/osm-yolo-crossings#3]
It would be nice to add at least a brief instruction on how to start the project to run locally.

I see a lot of files in the project that I need to explore into to run and set up the environment, but they are pretty hard to understand. For example, I see files from the Nix package manager requires research if encountering it for the first time. Yet it seems to be responsible for setting up the environment and installing packages.

**Comment by Zaczero** [comment]
Done https://github.com/Zaczero/osm-yolo-crossings#readme. Thank you!
