### ISSUE TITLE
Switch to OAuth 2.0

### ISSUE THREAD

**Issue by pnorman** [Zaczero/osm-yolo-crossings#7]
OSM is deprecating [OAuth 1.0a and HTTP Basic Auth](https://github.com/openstreetmap/operations/issues/867).

Your application was identified as making HTTP Basic Auth calls, which will stop working later this year. We are still working out a precise timeline.

**Comment by Zaczero** [comment]
I don't see the point of using OAuth in this kind of script application. This application does not require use of authorization flows. My account is the only user of it. Continuing the conversation [here](https://github.com/openstreetmap/operations/issues/867#issuecomment-1888122299).
